### ISSUE TITLE
MMORPG Feature List [~9+ Important Composite Depth To-Do Feature Requests]

### ISSUE THREAD

**Issue by WithinAmnesia** [SlayHorizon/godot-tiny-mmo-template#4]
[Work in Progress]

MMORPG Feature List:

0.) Colour Text Item Quality / Rarity
1.) WASD Flare / Zelda Style ARPG Combat Template Example
2.) Experience / Level Scaling
3.) Arbitrary Attributes / Statistics / Damage Types and Elements
4.) Arbitrary Resource System
5.) Floating Point / Percentage % / Complex Number Support
6.) Abilities / Powers
7.) Skilltrees / Powertrees
8.) Equipment Sets
9.) Step Sounds / Inventory Item Sounds
10.) Women and men gender selection and various appearance customization features per character.
11.) 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+? At least 16+ characters per account is ideal.
12.) An Adventurer (start with no features at the start) / 'default' / 'classless' class option like in osrs / oblivion?
13.) ~6 classes to pick at the start?:

    Adventurer (default / no features at the start / 'classless' / make your own class)
    Warrior (Melee dps / tank starter boost)
    Ranger / Wanderer (Ranged / bow dps starter boost)
    Wizard (Caster / dps starter boost)
    Warden / Cleric / Priest (Healer / support / dps start boost)
    Bard / Rogue / Worlder (Hybrid / dps / tank / healer jack of all trades boost)

14.) Multiclassing like in BG3/D&D?
15.) Hotswap classes / class choise freedom / respec classes freedom
16.) Classes that can just be titles and new classes can be changed into as options
17.) Multiboxing of up to 16 characters from 1 account on 1 client / player / computer
18.) Entity Commands /follow /stop /hostile /defensive /passive /heal_lowest_ally commands
19+ / Bonus.) More Feature Requests:
Arbitrary Attributes, Arbitrary Resources (e.g. Health, Spirit, Mana etc.), Arbitrary Abilities, Groups, Raids, Instances, Guilds, Storage, Banking, Trade, Auction House, Mail Box System, Player / Guild Housing, Customizable Player Decorations / Tabards / Images / Armour / Weapons / Items / Appearances / Objects etc., Building, Tradeskills, Gather Skills, Crafting Skills, Skills minigames (e.g. weave stitches to sew item etc.), PvP, 'Single Player' / 'Personal Server' / 'Offline / Dev Mode', Mounts, Pets, LIGHT cosmetic only monetization and website store guide, Game Masters, Moderation and forums, Account Security, 'Vehicles' (e.g. siege tower, catapult, ship, hot air balloon, wagon, chariot, 'tank', 'air ship' etc.), public transportation (e.g. boats, wagons, trains, griffins etc.), sieges with destructible walls / gates (e.g wintergrasp in wow / mount and blade banner lord / lord of the rings / history). Barber shop to customize hair appearance etc. 2.5D graphics, 3D graphics VR, physics, realistic ballistics etc., summon avatars like D&D and conan mmorpg, dynamic spawning / populating world, music and play instruments like bg3/D&D, player feature voting polls for big time open source forever free MMORPGs!

Notes from Discord (to help remember / archive thoughts):
"Horizon — Today at 16:26 [20th / 08 (August) / 2024]
I just updated the readme, what do you think about it? Especially the goals / to-list part?
Don't hesitate to make a pull request if you want to improve it and add licensing stuff or just suggest me things here
https://github.com/SlayHorizon/godot-tiny-mmo-template "
I have to figure out the proper questions but I've done a top 9 list before:

Here is Wyvern systems: https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/24
(Important Depth Features) [~'Clearer To-Do List']:
0.) Colour Text Item Quality / Rarity
1.) WASD Flare / Zelda Style ARPG Combat Template Example
2.) Experience / Level Scaling
3.) Arbitrary Attributes / Statistics / Damage Types and Elements
4.) Arbitrary Resource System
5.) Floating Point / Percentage % / Complex Number Support
6.) Abilities / Powers
7.) Skilltress / Powertrees
8.) Equipment Sets
9.) Step Sounds / Inventory Item Sounds
Here is JDungeon: https://github.com/jonathaneeckhout/jdungeon/issues/254
9+ Feature Requests (From ~Discord ~Internet):
1.) Can we have women and men gender selection and various appearance customization features per character?
2.) Can we have 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+? At least 16+ characters per account is ideal.
3.) Can we have an Adventurer (start with no features at the start) / 'default' / 'classless' class option like in osrs / oblivion?
4.) Can we have ~6 classes to pick at the start?:

    Adventurer (default / no features at the start / 'classless' / make your own class)
    Warrior (Melee dps / tank starter boost)
    Ranger / Wanderer (Ranged / bow dps starter boost)
    Wizard (Caster / dps starter boost)
    Warden / Cleric / Priest (Healer / support / dps start boost)
    Bard / Rogue / Worlder (Hybrid / dps / tank / healer jack of all trades boost)

5.) Can we have multiclassing like in BG3/D&D?
6.) Can we hotswap classes technically like in that demo you could selection 1 class load it up and play that with its own set of abilities can we bring that back as a hotswap to test things online? As like in the previous classes build demo press j to bring up class selection screen then swap to a class like ranger or caster to test abilities?
7.) Can we have classes that can just be titles and new classes can be changed into as options like unlocking new titles from hero orders and like D&D where classes can be added and changed later too? It makes it like legos for player choice and that's good for open source having those kinds of rpg options.
8.) Can we have multiboxing of up to 16 characters from 1 account on 1 client / player / computer like with bg3/infinity engine games/d2 merc/rts?
9.) Can we have /follow /stop /hostile /defensive /passive /heal_lowest_ally commands (akin to bg / wow combat pet commands) would go so far with group / multiboxing / rts features?
Bonus.) More Feature Requests:
Arbitrary Attributes, Arbitrary Resources (e.g. Health, Spirit, Mana etc.), Arbitrary Abilities, Groups, Raids, Instances, Guilds, Storage, Banking, Trade, Auction House, Mail Box System, Player / Guild Housing, Customizable Player Decorations / Tabards / Images / Armour / Weapons / Items / Appearances / Objects etc., Building, Tradeskills, Gather Skills, Crafting Skills, Skills minigames (e.g. weave stitches to sew item etc.), PvP, 'Single Player' / 'Personal Server' / 'Offline / Dev Mode', Mounts, Pets, LIGHT cosmetic only monetization and website store guide, Game Masters, Moderation and forums, Account Security, 'Vehicles' (e.g. siege tower, catapult, ship, hot air balloon, wagon, chariot, 'tank', 'air ship' etc.), public transportation (e.g. boats, wagons, trains, griffins etc.), sieges with destructible walls / gates (e.g wintergrasp in wow / mount and blade banner lord / lord of the rings / history). Barber shop to customize hair appearance etc. 2.5D graphics, 3D graphics VR, physics, realistic ballistics etc., summon avatars like D&D and conan mmorpg, dynamic spawning / populating world, music and play instruments like bg3/D&D, player feature voting polls for big time open source forever free MMORPGs!
So I'll have to look at where we are but those are past ones that come to mind.

Composite Feature List / (Important Depth Features) [~'Clearer To-Do List']:
0.) Colour Text Item Quality / Rarity
1.) WASD Flare / Zelda Style ARPG Combat Template Example
2.) Experience / Level Scaling
3.) Arbitrary Attributes / Statistics / Damage Types and Elements
4.) Arbitrary Resource System
5.) Floating Point / Percentage % / Complex Number Support
6.) Abilities / Powers
7.) Skilltrees / Powertrees
8.) Equipment Sets
9.) Step Sounds / Inventory Item Sounds
10.) Women and men gender selection and various appearance customization features per character.
11.) 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+? At least 16+ characters per account is ideal.
12.) An Adventurer (start with no features at the start) / 'default' / 'classless' class option like in osrs / oblivion?
13.) ~6 classes to pick at the start?:

    Adventurer (default / no features at the start / 'classless' / make your own class)
    Warrior (Melee dps / tank starter boost)
    Ranger / Wanderer (Ranged / bow dps starter boost)
    Wizard (Caster / dps starter boost)
    Warden / Cleric / Priest (Healer / support / dps start boost)
    Bard / Rogue / Worlder (Hybrid / dps / tank / healer jack of all trades boost)

14.) Multiclassing like in BG3/D&D?
15.) Hotswap classes / class choise freedom / respec classes freedom
16.) Classes that can just be titles and new classes can be changed into as options
17.) Multiboxing of up to 16 characters from 1 account on 1 client / player / computer
18.) Entity Commands /follow /stop /hostile /defensive /passive /heal_lowest_ally commands

Bonus.) More Feature Requests:
Arbitrary Attributes, Arbitrary Resources (e.g. Health, Spirit, Mana etc.), Arbitrary Abilities, Groups, Raids, Instances, Guilds, Storage, Banking, Trade, Auction House, Mail Box System, Player / Guild Housing, Customizable Player Decorations / Tabards / Images / Armour / Weapons / Items / Appearances / Objects etc., Building, Tradeskills, Gather Skills, Crafting Skills, Skills minigames (e.g. weave stitches to sew item etc.), PvP, 'Single Player' / 'Personal Server' / 'Offline / Dev Mode', Mounts, Pets, LIGHT cosmetic only monetization and website store guide, Game Masters, Moderation and forums, Account Security, 'Vehicles' (e.g. siege tower, catapult, ship, hot air balloon, wagon, chariot, 'tank', 'air ship' etc.), public transportation (e.g. boats, wagons, trains, griffins etc.), sieges with destructible walls / gates (e.g wintergrasp in wow / mount and blade banner lord / lord of the rings / history). Barber shop to customize hair appearance etc. 2.5D graphics, 3D graphics VR, physics, realistic ballistics etc., summon avatars like D&D and conan mmorpg, dynamic spawning / populating world, music and play instruments like bg3/D&D, player feature voting polls for big time open source forever free MMORPGs!

Matthew — Today at 17:44 [5:44 PM 20th / 08 (August) / 2024]
I'm a crazy experienced mmorpg / rpg dev too so like I should share that too like here's me with the Ashbringer in vanilla wow. Also here is myself as a pioneering Game Master / dev for private servers literally making the impossible possible (adding in new dungeons from blender .blend files straight into wow .wmo files) https://www.deviantart.com/withinamnesia/art/Game-Master-Veldryn-858651305 [That first step getting the community dev tools to work together and showing it can be done making a new dungeon / raid .wmo model file from blender for the first time lead to the flood gates opening and having private wow server make new content better than retail wow].
Here is myself with retail content on WoW [I gave a ton of concept art to freelance blizzard artists and found this sword years later on wowhead] https://www.wowhead.com/item=118080/admiral-taylors-greatsword
Here is myself with private server content on Turtle WoW [example new item model added to the game]: https://www.deviantart.com/withinamnesia/art/Greatsword-of-Omen-3D-Model-Blender-2-79-871967906
Also I was given the super collector's edition / here all the digital of Baldur's Gate Siege of Dragonspear by the studio after winning a contest / helping bug fix / adding content / helping Baldur's Gate devs too.
Also here is a funny clip of a day in the life of hardcore world first / best raiding: https://www.youtube.com/watch?v=mFors1WXgTM
I also do tank / military / history / world trade / geopolitics /  engineering / construction / heavy equipment / boats / submarines / space and aviation stuff if you like that so ya Its not easy to like quickly share what I can offer to give also I like helped unreal 5 get the community working on 4K-8K mmorpg templates but I backed out after China bought out Epic Games so I'm on Godot now lol. Please feel free to ask questions oh here is a cool speech I did to rally the troops / devs on unreal like 1k+ dev server to get cool mmorpg projects happening. Lots of stuff. 
[Who will rise to make ~'Grand RPGs' forever free.txt](https://github.com/user-attachments/files/16684612/Who.will.rise.to.make.Grand.RPGs.forever.free.txt)
![All Hail To The King Baby!](https://github.com/user-attachments/assets/33cccc80-3490-4bdd-877f-015e175585ab)

**Comment by WithinAmnesia** [comment]
I'll try for a more compact and easy to read / better sharability version of all of these critical points and in depth features and story time. Lots to do and I think this is getting better bit by bit. Stay positive and things will get better it just takes the ability to keep fighting the good fight and productive time.

**Comment by WithinAmnesia** [comment]
Notes, total list of readme feature (archive to keep track of extra details:

Readme Draft Version:
- [X] 1.) **Client-Server connection through WebSocketMultiplayerPeer.**
- [ ] 2.) **Client side working on web browser.**
- [X] 3.) **Authentication steps before connecting.**
- [ ] 4.) **Login UI to authenticate.**
- [ ] 5.) **Player character selection log in screen (16+ characters per account).**
- [ ] 6.) **Multiboxing of up to 16 characters from 1 account on 1 client / player / computer.**
- [X] 7.) **Synchronizing entities among the players in the same instance.**
- [X] 8.) **Hosting different map instances on a single server and allowing traveling between them.**
- [ ] 9.) **Private instance for individual players or groups.**
- [ ] 10.) **WASD Flare Style ARPG Combat combat system with PvE and PvP.**
- [ ] 11.) **Abilities / powers / spells.**
- [ ] 12.) **Hotbar GUI support ability / power / spell.**
- [ ] 13.) **Entity commands (/follow /stop /hostile /defensive /passive /heal_lowest_ally command).**
- [ ] 14.) **Multiple class build starts to choose at the beginning (Adventurer/Worlder/Multiclass/Build-a-class/Default, Warrior/Knight, Wanderer/Rogue, Wizard/Mage, Warden/Cleric).**
- [ ] 15.) **Experience, character progression / leveling and specialization / skilltrees / powertrees.**
- [ ] 16.) **Arbitrary attributes / statistics / damage types and elements.**
- [ ] 17.) **Arbitary entity resource (Health, Mana, Spirit etc.).**
- [X] 18.) **Floating Point / Percentage % / Complex Number Support.**
- [ ] 19.) **Character / player customization (men and women gender selection and various appearance customization features per character).**
- [ ] 20.) **Visual chararcter equipment and arbitrary character equipment slots.**
- [ ] 21.) **Inventory and item storage with arbitrary inventory and item storage slots.**
- [ ] 22.) **Colour text item quality / rarity.**
- [ ] 23.) **Trade, auction house, in-game mail and economy.**
- [ ] 24.) **Step Sounds / Inventory Item Sounds.**
- [ ] 25.) **Equipment sets.**
- [5/25] 20% Feature complete progress.)

Readme Public Version.
- [X] **Client-Server connection through WebSocketMultiplayerPeer.**
- [ ] **Client side working on web browser.**
- [X] **Authentication steps before connecting.**
- [ ] **Login UI to authenticate.**
- [ ] **Player character customization.**
- [X] **Synchronizing entities among the players in the same instance.**
- [X] **Hosting different map instances on a single server and allowing traveling between them.**
- [ ] **Private instance for individual players or groups.**
- [ ] **Multiple character class (Warrior/Knight, Archer/Rogue, Wizard/Mage, Warden/Cleric).**
- [ ] **Experience and leveling.**
- [ ] **Mobs hosted and managed by the server.**
- [ ] **Basic combat system with PvE and PvP.**
- [ ] **Arbitary entity resource (Health, Mana etc.).**. 
And probably more later.

**Comment by WithinAmnesia** [comment]
![image](https://github.com/user-attachments/assets/ed1d527e-d05f-4f57-abd8-2d5af9227839)
Chat is looking good! I suppose world chat / other channels should be listed as a feature to suggest. This chat is really good so far, good job!

**Comment by SlayHorizon** [comment]
Thanks! I tried to make it as minimal as possible, so there's a lot that can be added to it.
What do you mean by other channels and what the mail and other things would look like ? 
If you have any sketches or examples, feel free to send them

**Comment by WithinAmnesia** [comment]
> Thanks! I tried to make it as minimal as possible, so there's a lot that can be added to it. What do you mean by other channels and what the mail and other things would look like ? If you have any sketches or examples, feel free to send them

World of Warcraft's chat system is very good balance of minimum but lots of deep and powerful features yet they are easy to operate / understand to learn for new people too.
https://static.wikia.nocookie.net/wowwiki/images/0/06/Patch_5_1-Chat_window.jpg/revision/latest?cb=20121221170759
https://wowwiki-archive.fandom.com/wiki/Chat

WoW chat has channels. For example 'World' channel is server wide / faction wide, then each zone has a local channel like 'Honeywood Forest' (kinda like how your room / map specific chat works where only players in that area can hear / have access to that local chat channel and 'the local chat channel' changes to the player's current zone. So like for example if adventuring in 'Honeywood Forest' you could /yell (red chat text that yell across the zone) 'Looking For Help with Wanted: Chomper group elite quest *links item rewards to help motivate people to organically join the group or maybe do a dungeon run.*
Whisper is /whisper <play_name> for private messages. Also 'Trade' channel chat for major cities linked together share a chat channel.
Chat can be made into windows for each channel if wanted / tab toggled to find the messages to read and share in the available chat channels to the player. Also /guild channel for <guild name here> guild member only chat channel is critical for MMOs also the guild text should be green for the best good times *big thumbs up* lol.
Here is the vanilla wow chat wiki link: https://wowwiki-archive.fandom.com/wiki/Chat
World

**Comment by WithinAmnesia** [comment]
![M M O A R P G (V 000 058) Godot-Tiny-MMO-Demo-0 0 20 Godot 4 3 NET+ Godot Tiny MMO (0)](https://github.com/user-attachments/assets/4991da6c-6b7b-4726-9d7e-48590314a476)
Looking good so far! Just bulldozing forward! This is a really big step forward. Lots of wind in the sails heading in the right direction. Keep it up, so its really excellent and has tonnes of potential!
